version: '3.8'

services:
  gooddentist:
    image: gooddentist:latest
    build:
      context: .
      dockerfile: GoodDentist/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=tcp:goodentist.database.windows.net,1433;Initial Catalog=Good_Dentist_DB;Persist Security Info=False;User ID=admin1;Password=Nhat2003.;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

  redis:
    image: redis:6.0.3
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

volumes:
  redis_volume_data:
